theme: jekyll-theme-slate

collections:
  notes:
    output: true
    permalink: /:path
  topics:
    output: true
    permalink: /:path

    
defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic_bs4grid"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note_bs4grid"
  - scope:
      path: ""
    values:
      layout: "default_bs4grid"