theme: jekyll-theme-slate

collections:
  notes:
    output: true
    permalink: /:path
  topics:
    output: true

    
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
    values:
      layout: "default"